### ISSUE TITLE
What content should be put in .csslintrc?

### ISSUE THREAD

**Issue by calfzhou** [ebednarz/csslintrc#1]
According to CSSLint document about [command line interface](https://github.com/CSSLint/csslint/wiki/Command-line-interface), it is used to define command line arguments, such as:

```
--errors=important
--warnings=import
```

But your `.csslintrc` contains json data about each rule's disable/enable. It really works, but I couldn't find any document about this.

**Comment by ebednarz** [comment]
@calfzhou 
Sorry, vacation period. I didn't even know that this repo was linked in the CSSLint documentation. I think it would be best to file an issue with CSSLint to improve the documentation. [Parsing JSON is clearly implemented](https://github.com/CSSLint/csslint/blob/f69cf12e23ca95cfd9e78a4a5d83fdccb71bb8be/src/cli/common.js#L311) and .csslintrc files are used by a lot of projects, e.g. [Twitter Bootstrap](https://github.com/twbs/bootstrap/blob/master/less/.csslintrc).

If memory serves, I know about it by watching [the related CSSLint issue](https://github.com/CSSLint/csslint/issues/359).
